GFX1151 inline asm compilation error (#909)
Encountered the below errors originally running with a local build of
MIOpen , running PyTorch wheels to run TTS model training.
Investigation shows similar - https://github.com/ROCm/MIOpen/issues/1528

This is a PR applying similar changes to this PR:
https://github.com/ROCm/MIOpen/pull/1531/files to add necessary fixes.

:14:20: error: not a valid operand.
v_add_f32 v3 v3 v3 row_bcast:15 row_mask:0xa
^
:15:23: error: not a valid operand.
v_add_f32 v16 v16 v16 row_bcast:15 row_mask:0xa
^
:17:20: error: not a valid operand.
v_add_f32 v3 v3 v3 row_bcast:31 row_mask:0xc
^
:18:23: error: not a valid operand.
v_add_f32 v16 v16 v16 row_bcast:31 row_mask:0xc
^
MIOpen(HIP): Error [Do] 'amd_comgr_do_action(kind, handle,
in.GetHandle(), out.GetHandle())' : ERROR (1)
MIOpen(HIP): Error [BuildOcl] comgr status = ERROR (1)
MIOpen(HIP): Warning [BuildOcl] error: cannot compile inline asm
error: cannot compile inline asm
error: cannot compile inline asm
error: cannot compile inline asm
4 errors generated

---
🔁 Imported from
[ROCm/MIOpen#3796](https://github.com/ROCm/MIOpen/pull/3796)
🧑‍💻 Originally authored by @ivandobskygithub

---------

Signed-off-by: Artem Kuzmitckii <artem.kuzmitckii@amd.com>
Co-authored-by: ivandobskygithub <84400859+ivandobskygithub@users.noreply.github.com>
Co-authored-by: BradPepersAMD <Brad.Pepers@amd.com>
Co-authored-by: ivandobskygithub <github@dobsky.com>
Co-authored-by: assistant-librarian[bot] <assistant-librarian[bot]@users.noreply.github.com>
Co-authored-by: Slobodan Josic <slojosic@amd.com>
Co-authored-by: Slobodan Josic <127323561+slojosic-amd@users.noreply.github.com>
Co-authored-by: Artem Kuzmitckii <artem.kuzmitckii@amd.com>