[hipDNN] Fix StaticCast header issues from install (#2440)
## Motivation

StaticCast header was breaking sample builds due to following error's:

```
/opt/rocm/include/hipdnn/sdk/hipdnn_sdk/utilities/StaticCast.hpp:34:18: error: template-id 'from<double>' in declaration of primary template
34 | hip_bfloat16 from<double>(double value)
| ^~~~~~~~~~~~
/opt/rocm/include/hipdnn/sdk/hipdnn_sdk/utilities/StaticCast.hpp:39:15: error: explicit specialization in non-namespace scope 'struct hipdnn_sdk::utilities::detail::CastTo<hip_bfloat16>'
39 | template <>
| ^
```

Swap instead to typed overloads.