[hipblaslt] Fix an error with DirectToVgprA + DirectToLds (#3481)
## Motivation

Fix an error when running tensilelite with DirectToVgpr+DirectToLds

## Technical Details

Fixed the following error.
```
  File "penv/lib/python3.12/site-packages/Tensile/KernelWriter.py", line 2298, in noLoadLoopBody
    waitLWCode.add(self.getWaitcntCodeForDirectToVgpr(kernel, localWriteEndIter, u, isNLL=(not isNGLL), beforeBarrier=True))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: KernelWriterAssembly.getWaitcntCodeForDirectToVgpr() missing 2 required positional arguments: 'localWriteEndIter' and 'u'
```

## Test Plan

Added a new test case in dtl.yaml to cover this combination.

## Test Result

Failed without fix.
Passed with this fix.

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.