[hipDNN] Rename remaining knob_id_str to knob_id (#4116)
## Motivation

Fixed build issues after merge conflicts:
https://github.com/ROCm/rocm-libraries/pull/4105 and
https://github.com/ROCm/rocm-libraries/pull/3982:
```
/opt/rocm-libraries-full/projects/hipdnn/tests/backend/IntegrationKnobsApi.cpp:159:18: error: no member named 'knob_id_str' in 'hipdnn_data_sdk::data_objects::Knob'
  159 |         if(knob->knob_id_str()->str() == "test.int_knob")
      |            ~~~~  ^
/opt/rocm-libraries-full/projects/hipdnn/tests/backend/IntegrationKnobsApi.cpp:220:18: error: no member named 'knob_id_str' in 'hipdnn_data_sdk::data_objects::Knob'
  220 |         if(knob->knob_id_str()->str() == "test.float_knob")
      |            ~~~~  ^
/opt/rocm-libraries-full/projects/hipdnn/tests/backend/IntegrationKnobsApi.cpp:280:18: error: no member named 'knob_id_str' in 'hipdnn_data_sdk::data_objects::Knob'
  280 |         if(knob->knob_id_str()->str() == "test.string_knob")
      |            ~~~~  ^
/opt/rocm-libraries-full/projects/hipdnn/tests/backend/IntegrationKnobsApi.cpp:350:18: error: no member named 'knob_id_str' in 'hipdnn_data_sdk::data_objects::Knob'
  350 |         if(knob->knob_id_str()->str() == "test.deprecated_knob")
      |            ~~~~  ^
4 errors generated.
```

## Technical Details

Rename remaining `knob_id_str` to `knob_id`

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.